#!/bin/bash

#SBATCH -J assn8       # Job name
#SBATCH -o assn8.o%j   # Name of stdout output file(%j expands to jobId)
#SBATCH -e assn8.o%j   # Name of stderr output file(%j expands to jobId)
#SBATCH -p development           # Submit to the 'normal' or 'development' queue
#SBATCH -N 1                # Total number of nodes requested (16 cores/node)
#SBATCH -n 1                # Total number of mpi tasks requested
#SBATCH -t1:00         # Run time (hh:mm:ss) - 1.5 hours

#SBATCH -A TG-ASC140030 	# <-- Allocation name to charge job against!

# This example will run an OpenMP application using 16 threads

# Set the number of threads per task(Default=1)
export OMP_NUM_THREADS=16

# Run the OpenMP application
./assn8 1600000000 8
